from enum import StrEnum


class DataMode(StrEnum):
    LIVE = "LIVE"
    CACHED = "CACHED"
    SYNTHETIC = "SYNTHETIC"


class CalculationStatus(StrEnum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    STALE = "STALE"
    BLOCKED = "BLOCKED"


class ClaimType(StrEnum):
    DIRECT_OBSERVATION = "direct_observation"
    REPORT_CATALOG = "context/report_catalog"
    CONTEXT = "context"
    CONDITIONAL_SCENARIO = "conditional_scenario"
    DIAGNOSTIC = "diagnostic"


class ErrorCode(StrEnum):
    MODE_NOT_ALLOWED = "MODE_NOT_ALLOWED"
    LIVE_NOT_ENABLED = "LIVE_NOT_ENABLED"
    FIXTURE_DATA = "FIXTURE_DATA"
    UNKNOWN_AGE = "UNKNOWN_AGE"
    NO_OBSERVATION = "NO_OBSERVATION"
    NO_COVERAGE = "NO_COVERAGE"
    STALE_DATA = "STALE_DATA"
    DIRECTION_UNVERIFIED = "DIRECTION_UNVERIFIED"
    NO_COMPATIBLE_SOURCE = "NO_COMPATIBLE_SOURCE"
    MODEL_BLOCKED = "MODEL_BLOCKED"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    ZONE_NOT_FOUND = "ZONE_NOT_FOUND"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    ZONE_VERSION_MISMATCH = "ZONE_VERSION_MISMATCH"
    DOMAIN_INSUFFICIENT = "DOMAIN_INSUFFICIENT"
    GATE_MAPPING_BLOCKED = "GATE_MAPPING_BLOCKED"
    UPSTREAM_AUTH_FAILED = "UPSTREAM_AUTH_FAILED"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
